name: Reddit Clone CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Set up Docker CLI
      uses: docker/login-action@v1
      with:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        registry: https://index.docker.io/v1/

    - name: Build Docker Image
      run: docker build -t shivani1711/reddit-clone:latest .
      
    - name: Push Docker Image
      run: docker push shivani1711/reddit-clone:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to Minikube
      run: |
        kubectl apply -f /home/ubuntu/k8s-reddit-clone/deployment.yaml
        kubectl apply -f /home/ubuntu/k8s-reddit-clone/service.yaml

env:
  DOCKER_CLI_AGGREGATE: 1
  DOCKER_BUILDKIT: 1
